import React from 'react';
import SEO from '../components/SEO';

export default function PreviewHub() {
  return (
    <div className="py-16 sm:py-24 px-4 sm:px-8">
      <SEO
        title="Get a Free Preview | LevelUp Ecosystem"
        description="See your new website before you decide. Choose between an instant AI draft or a custom preview designed and reviewed by me."
        noindex={true}
      />

      {/* Hero Header */}
      <div className="max-w-3xl mx-auto text-center space-y-4 mb-14 sm:mb-20">
        <span className="text-xs font-bold uppercase tracking-wider text-[#A78BFA]">
          Free Website Preview
        </span>
        <h1 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight">
          Get a free preview of your website
        </h1>
        <p className="text-base sm:text-lg text-[#A1A1B5] max-w-xl mx-auto leading-relaxed">
          See your new site before you decide. No obligation.
        </p>
      </div>

      {/* Two Choice Cards */}
      <div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 items-stretch">
        
        {/* Card 1: Instant Preview */}
        <div className="rounded-3xl bg-[#14141F] border border-white/[0.08] p-8 sm:p-10 flex flex-col justify-between relative transition-all duration-200 hover:border-white/[0.16]">
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold px-3 py-1 rounded-full bg-white/[0.08] text-[#A1A1B5]">
                Generated by AI
              </span>
              <span className="text-xs text-[#71717A] font-mono">~1 min</span>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-2">Instant preview</h2>
              <p className="text-sm text-[#A1A1B5] leading-relaxed">
                A quick draft created automatically in about a minute. Great for getting an idea of the look and feel.
              </p>
            </div>

            <ul className="space-y-3 pt-2 text-sm text-[#A1A1B5]">
              <li className="flex items-start gap-3">
                <span className="text-[#A78BFA] font-bold">✓</span>
                <span>Ready in ~1 minute</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-[#A78BFA] font-bold">✓</span>
                <span>Based on your business info</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-[#A78BFA] font-bold">✓</span>
                <span>Basic draft, not final design</span>
              </li>
            </ul>
          </div>

          <div className="pt-8">
            <a
              href="/preview/instant"
              className="w-full inline-flex items-center justify-center py-3.5 px-6 rounded-full bg-white/[0.08] hover:bg-white/[0.14] text-white font-semibold text-sm transition-all duration-200 cursor-pointer"
            >
              Generate my preview
            </a>
          </div>
        </div>

        {/* Card 2: Custom Preview (Highlighted / Most Popular) */}
        <div className="rounded-3xl bg-[#14141F] border-2 border-[#7C3AED] p-8 sm:p-10 flex flex-col justify-between relative shadow-[0_0_35px_rgba(124,58,237,0.18)]">
          {/* Most Popular Badge */}
          <div className="absolute -top-3.5 right-8">
            <span className="bg-[#7C3AED] text-white text-xs font-bold px-3.5 py-1 rounded-full uppercase tracking-wider shadow-sm">
              Most popular
            </span>
          </div>

          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold px-3 py-1 rounded-full bg-[#7C3AED]/20 text-[#DDD6FE] border border-[#7C3AED]/30">
                Designed by me, using AI tools
              </span>
              <span className="text-xs text-[#A78BFA] font-mono">24–48h</span>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-2">Custom preview</h2>
              <p className="text-sm text-[#A1A1B5] leading-relaxed">
                I design and review a preview for your business and send it to your email.
              </p>
            </div>

            <ul className="space-y-3 pt-2 text-sm text-[#A1A1B5]">
              <li className="flex items-start gap-3">
                <span className="text-[#7C3AED] font-bold">✓</span>
                <span className="text-white font-medium">Ready in 24 to 48 business hours</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-[#7C3AED] font-bold">✓</span>
                <span>Reviewed and tested by me</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-[#7C3AED] font-bold">✓</span>
                <span>Sent to your email as a private link</span>
              </li>
            </ul>
          </div>

          <div className="pt-8">
            <a
              href="/preview/custom"
              className="w-full inline-flex items-center justify-center py-3.5 px-6 rounded-full bg-[#7C3AED] hover:bg-[#8B5CF6] text-white font-semibold text-sm transition-all duration-200 shadow-md shadow-[#7C3AED]/25 cursor-pointer"
            >
              Request my custom preview
            </a>
          </div>
        </div>

      </div>

      {/* Small Note Under the Cards */}
      <div className="max-w-xl mx-auto text-center mt-12">
        <p className="text-xs text-[#71717A] leading-relaxed">
          AI tools help me build faster. Every custom preview is directed and reviewed by me.
        </p>
      </div>
    </div>
  );
}
