import React, { useState } from 'react';
import SEO from '../components/SEO';

export default function PreviewInstant() {
  const [businessName, setBusinessName] = useState('');
  const [businessType, setBusinessType] = useState('Barbershop');
  const [city, setCity] = useState('');
  const [services, setServices] = useState('');
  const [colors, setColors] = useState('');
  const [socialLink, setSocialLink] = useState('');

  const [activeTab, setActiveTab] = useState<'form' | 'demo'>('form');
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitted(true);
  };

  return (
    <div className="py-16 sm:py-24 px-4 sm:px-8">
      <SEO
        title="Instant Website Preview | LevelUp Ecosystem"
        description="Generate an instant AI draft of your website in ~1 minute. Basic draft for look and feel."
        noindex={true}
      />

      <div className="max-w-3xl mx-auto">
        
        {/* Navigation Breadcrumb */}
        <div className="mb-8 text-center sm:text-left">
          <a
            href="/preview"
            className="text-xs font-semibold text-[#A78BFA] hover:text-white transition-colors inline-flex items-center gap-1.5"
          >
            ← Back to preview options
          </a>
        </div>

        {/* Header */}
        <div className="text-center sm:text-left space-y-3 mb-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/[0.08] text-[#A1A1B5] text-xs font-semibold">
            <span>Generated by AI</span>
            <span className="text-[#71717A]">•</span>
            <span className="text-[#A78BFA]">Automated pipeline</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
            Instant website preview
          </h1>
          <p className="text-sm sm:text-base text-[#A1A1B5] leading-relaxed">
            Create an automated first draft in about a minute. Great for visualizing initial layout, services, and color scheme.
          </p>
        </div>

        {/* Tab Switcher: Form vs Sample Template Preview */}
        <div className="flex items-center gap-2 mb-8 p-1.5 rounded-2xl bg-[#14141F] border border-white/[0.08] w-fit mx-auto sm:mx-0">
          <button
            type="button"
            onClick={() => setActiveTab('form')}
            className={`px-4 py-2 rounded-xl text-xs font-semibold transition-all ${
              activeTab === 'form'
                ? 'bg-[#7C3AED] text-white shadow-sm'
                : 'text-[#A1A1B5] hover:text-white'
            }`}
          >
            Preview Generator
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('demo')}
            className={`px-4 py-2 rounded-xl text-xs font-semibold transition-all ${
              activeTab === 'demo'
                ? 'bg-[#7C3AED] text-white shadow-sm'
                : 'text-[#A1A1B5] hover:text-white'
            }`}
          >
            View Sample AI Draft
          </button>
        </div>

        {activeTab === 'demo' ? (
          /* Sample AI Draft Template with Watermark */
          <div className="rounded-3xl bg-[#14141F] border border-white/[0.08] p-6 sm:p-8 space-y-8 relative overflow-hidden">
            {/* Diagonal Preview Watermark */}
            <div
              className="absolute inset-0 flex items-center justify-center pointer-events-none select-none z-20 opacity-[0.06] text-8xl font-black rotate-[-25deg] uppercase tracking-widest text-white"
              aria-hidden="true"
            >
              PREVIEW
            </div>

            {/* Top Draft Notice */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-4 rounded-2xl bg-[#0B0B14] border border-white/[0.08] relative z-10">
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-1 rounded bg-[#7C3AED]/20 text-[#A78BFA] text-[11px] font-bold uppercase tracking-wider">
                  AI-generated draft
                </span>
                <span className="text-xs text-[#71717A]">Expires in 7 days</span>
              </div>
              <a
                href="/preview/custom"
                className="text-xs text-[#A78BFA] hover:text-white underline font-medium"
              >
                Want a custom version? Request a custom preview
              </a>
            </div>

            {/* Mock Draft Content */}
            <div className="space-y-6 relative z-10">
              <div className="border-b border-white/[0.08] pb-6 space-y-2">
                <div className="text-xs uppercase tracking-wider text-[#A78BFA] font-bold">Sample Instant Output</div>
                <h3 className="text-2xl font-bold text-white">Crown & Edge Barber Lounge</h3>
                <p className="text-sm text-[#A1A1B5] leading-relaxed">
                  Precision grooming, tailored cuts, and beard artistry in an elevated, modern sanctuary.
                </p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="p-4 rounded-2xl bg-[#0B0B14] border border-white/[0.06]">
                  <h4 className="text-sm font-bold text-white mb-1">Signature Fade</h4>
                  <p className="text-xs text-[#A1A1B5]">Custom haircut with hot towel treatment and razor edge finish.</p>
                </div>
                <div className="p-4 rounded-2xl bg-[#0B0B14] border border-white/[0.06]">
                  <h4 className="text-sm font-bold text-white mb-1">Beard Sculpt</h4>
                  <p className="text-xs text-[#A1A1B5]">Precision lining, conditioning oils, and shape sculpting.</p>
                </div>
                <div className="p-4 rounded-2xl bg-[#0B0B14] border border-white/[0.06]">
                  <h4 className="text-sm font-bold text-white mb-1">VIP Package</h4>
                  <p className="text-xs text-[#A1A1B5]">Full haircut, beard grooming, facial massage, and styling.</p>
                </div>
              </div>

              <div className="pt-4 text-center">
                <a
                  href="/preview/custom"
                  className="inline-flex items-center justify-center py-3 px-6 rounded-full bg-[#7C3AED] hover:bg-[#8B5CF6] text-white text-xs font-semibold transition-all"
                >
                  Request a custom review for your business
                </a>
              </div>
            </div>
          </div>
        ) : submitted ? (
          /* Submitted State with Coming Soon Notification */
          <div className="rounded-3xl bg-[#14141F] border border-[#7C3AED]/40 p-8 sm:p-12 text-center space-y-6 shadow-[0_0_35px_rgba(124,58,237,0.15)]">
            <div className="inline-block px-3.5 py-1.5 rounded-full bg-[#7C3AED]/20 text-[#DDD6FE] text-xs font-semibold border border-[#7C3AED]/30">
              Instant Generation Engine: Coming Soon
            </div>

            <div className="space-y-3">
              <h2 className="text-2xl font-bold text-white">
                The instant AI generator is currently in early preview
              </h2>
              <p className="text-sm text-[#A1A1B5] max-w-lg mx-auto leading-relaxed">
                The automated pipeline requires secure API rate limits and template sandboxing. In the meantime, I can build and review your custom preview personally!
              </p>
            </div>

            <div className="p-5 rounded-2xl bg-[#0B0B14] border border-white/[0.08] max-w-md mx-auto text-left text-xs text-[#A1A1B5] space-y-2">
              <div className="font-semibold text-white">How the instant generator works:</div>
              <ul className="list-disc pl-4 space-y-1">
                <li>Input data is sanitized and strictly validated.</li>
                <li>An LLM generates strict JSON (no raw HTML injection).</li>
                <li>Content is injected into pre-designed responsive templates.</li>
                <li>Output is protected with rate limits and an automatic 7-day expiration.</li>
              </ul>
            </div>

            <div className="pt-2 flex flex-wrap items-center justify-center gap-4">
              <a
                href="/preview/custom"
                className="py-3 px-6 rounded-full bg-[#7C3AED] hover:bg-[#8B5CF6] text-white text-xs font-semibold transition-all"
              >
                Request my custom preview (24-48h)
              </a>
              <button
                type="button"
                onClick={() => setSubmitted(false)}
                className="py-3 px-6 rounded-full bg-white/[0.08] hover:bg-white/[0.12] text-white text-xs font-semibold transition-colors"
              >
                Edit info
              </button>
            </div>
          </div>
        ) : (
          /* Instant Preview Generator Form */
          <form onSubmit={handleSubmit} className="rounded-3xl bg-[#14141F] border border-white/[0.08] p-6 sm:p-10 space-y-6">
            <div className="p-4 rounded-2xl bg-[#0B0B14] border border-[#7C3AED]/30 flex items-start gap-3 text-xs text-[#A1A1B5]">
              <span className="text-[#A78BFA] text-base leading-none">💡</span>
              <div>
                <strong className="text-white">Quick Draft:</strong> This will generate a basic layout structure. For a complete, personalized website with custom booking integrations, choose the <a href="/preview/custom" className="text-[#A78BFA] underline">Custom preview</a>.
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-white">Business Name *</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Skyline Fade Lounge"
                  value={businessName}
                  onChange={(e) => setBusinessName(e.target.value)}
                  className="w-full bg-[#0B0B14] border border-white/[0.1] rounded-xl px-4 py-2.5 text-base sm:text-sm text-white placeholder-slate-500 focus:outline-none focus:border-[#7C3AED]"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-white">Business Type *</label>
                <select
                  value={businessType}
                  onChange={(e) => setBusinessType(e.target.value)}
                  className="w-full bg-[#0B0B14] border border-white/[0.1] rounded-xl px-4 py-2.5 text-base sm:text-sm text-white focus:outline-none focus:border-[#7C3AED]"
                >
                  <option value="Barbershop">Barbershop</option>
                  <option value="Hair or Nail Salon">Hair or Nail Salon</option>
                  <option value="Med Spa or Wellness">Med Spa or Wellness</option>
                  <option value="Restaurant or Cafe">Restaurant or Cafe</option>
                  <option value="Personal Trainer or Gym">Personal Trainer or Gym</option>
                  <option value="Creative Portfolio">Creative Portfolio</option>
                  <option value="Local Contractor or Trades">Local Contractor or Trades</option>
                  <option value="Other">Other Business</option>
                </select>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-white">City *</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. San Diego, Denver, Chicago..."
                  value={city}
                  onChange={(e) => setCity(e.target.value)}
                  className="w-full bg-[#0B0B14] border border-white/[0.1] rounded-xl px-4 py-2.5 text-base sm:text-sm text-white placeholder-slate-500 focus:outline-none focus:border-[#7C3AED]"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-white">Preferred Colors (Optional)</label>
                <input
                  type="text"
                  placeholder="Dark slate and violet, black and gold..."
                  value={colors}
                  onChange={(e) => setColors(e.target.value)}
                  className="w-full bg-[#0B0B14] border border-white/[0.1] rounded-xl px-4 py-2.5 text-base sm:text-sm text-white placeholder-slate-500 focus:outline-none focus:border-[#7C3AED]"
                />
              </div>
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-white">Services Offered (Short list) *</label>
              <textarea
                required
                rows={2}
                placeholder="e.g. Men's haircuts, beard grooming, hot towel shave..."
                value={services}
                onChange={(e) => setServices(e.target.value)}
                className="w-full bg-[#0B0B14] border border-white/[0.1] rounded-xl px-4 py-2.5 text-base sm:text-sm text-white placeholder-slate-500 focus:outline-none focus:border-[#7C3AED]"
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-white">Existing Instagram or Website (Optional)</label>
              <input
                type="text"
                placeholder="instagram.com/yourbusiness"
                value={socialLink}
                onChange={(e) => setSocialLink(e.target.value)}
                className="w-full bg-[#0B0B14] border border-white/[0.1] rounded-xl px-4 py-2.5 text-base sm:text-sm text-white placeholder-slate-500 focus:outline-none focus:border-[#7C3AED]"
              />
            </div>

            <div className="pt-2">
              <button
                type="submit"
                className="w-full py-3.5 px-6 rounded-full bg-[#7C3AED] hover:bg-[#8B5CF6] text-white font-semibold text-sm transition-all duration-200 cursor-pointer shadow-md shadow-[#7C3AED]/25"
              >
                Generate my preview
              </button>
            </div>

            <p className="text-[11px] text-[#71717A] text-center">
              Takes ~1 minute to render. AI drafts are for visual exploration and expire after 7 days.
            </p>
          </form>
        )}

      </div>
    </div>
  );
}
